default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: strangers_in_kind_dev

test:
  <<: *default
  database: strangers_in_kind_test

production:
  <<: *default
  database: strangers_in_kind_prod
